### ISSUE TITLE
Dancer2::Plugin::LogReport breaks after Dancer2 upgrade from 0.200003

### ISSUE THREAD

**Issue by biafra** [PerlDancer/Dancer2#1225]
After upgrading to 0.201000 using the LogReport plugin in other modules crashed with:

Can't call method "app" on an undefined value at /home/dancer2/lib/perl5/Dancer2/Plugin.pm line 486.

I'm using it essencially to internationalization and logging.

I created a test app with

$ dancer2 gen -a MyApp

and then edited lib/MyApp.pm as

```
package MyApp;

use Log::Report ();

use Dancer2;
use Dancer2::Plugin::LogReport 'com_xpto', mode => 'DEBUG';

use MyModule;

our $VERSION = '0.1';

get '/' => sub {
    template 'index';
};

true;

```

and MyModule.pm like this:

```
package MyModule;

use Log::Report ();

use Dancer2;

use Dancer2::Plugin::LogReport 'com_xpto', mode => 'DEBUG';

1;

```

This is the error when you try to run it:

```
dancer2@ankh-morpork:~/MyApp$ perl bin/app.psgi 
Plugin DSL method 'hook' is deprecated. Use '$self->app->add_hook' instead'.
 at /home/dancer2/MyApp/bin/../lib/MyApp.pm line 6.
Plugin DSL method 'hook' is deprecated. Use '$self->app->add_hook' instead'.
 at /home/dancer2/MyApp/bin/../lib/MyApp.pm line 6.
trace: switching to run mode 3 for Log::Report::Dispatcher::Callback, accept ALL
trace: switching to run mode 3 for Log::Report::Dispatcher::Perl, accept ALL
trace: switching to run mode 3 for Log::Report::Dispatcher::Callback, accept ALL
Can't call method "app" on an undefined value at /home/dancer2/lib/perl5/Dancer2/Plugin.pm line 486.
BEGIN failed--compilation aborted at /home/dancer2/MyApp/bin/../lib/MyModule.pm line 7.
Compilation failed in require at /home/dancer2/MyApp/bin/../lib/MyApp.pm line 8.
BEGIN failed--compilation aborted at /home/dancer2/MyApp/bin/../lib/MyApp.pm line 8.
Compilation failed in require at bin/app.psgi line 8.
BEGIN failed--compilation aborted at bin/app.psgi line 8.

```

After reinstalling 0.200003 it worked smoothly.

Thank you!

**Comment by xsawyerx** [comment]
Thank you, Jello. We'll create a test out of it and fix it.

**Comment by xsawyerx** [comment]
I'm not getting this error, but the second module loading the plugin again causes the routing to get screwed up. Not sure why or how yet. I want to say "take it up with the plugin author", but I've dealt with plugins quite a bit recently so now I'm intrigued.

**Comment by biafra** [comment]
Thank you for your troubleshooting!

2016-08-12 1:13 GMT+01:00 Sawyer X <notifications@github.com>:

**Comment by xsawyerx** [comment]
So I have a test I've written for this, based on your code. But it passes. Is that right? I can put it on a branch, but could you please test *master* branch?

**Comment by biafra** [comment]
It's working ok with 0.203001 from CPAN and from cloning the master here. I already upgrade my system and it's running smoothly. The output from the test app that I provided is the same with the two versions.

dancer2@ankh-morpork:~/MyApp$ perl bin/app.psgi 
Plugin DSL method 'hook' is deprecated. Use '$self->app->add_hook' instead'.
 at /home/dancer2/MyApp/bin/../lib/MyApp.pm line 6.
Plugin DSL method 'hook' is deprecated. Use '$self->app->add_hook' instead'.
 at /home/dancer2/MyApp/bin/../lib/MyApp.pm line 6.
trace: switching to run mode 3 for Log::Report::Dispatcher::Callback, accept ALL
trace: switching to run mode 3 for Log::Report::Dispatcher::Perl, accept ALL
trace: switching to run mode 3 for Log::Report::Dispatcher::Callback, accept ALL
Plugin DSL method 'hook' is deprecated. Use '$self->app->add_hook' instead'.
 at /home/dancer2/MyApp/bin/../lib/MyModule.pm line 7.
Plugin DSL method 'hook' is deprecated. Use '$self->app->add_hook' instead'.
 at /home/dancer2/MyApp/bin/../lib/MyModule.pm line 7.
trace: reopening dispatcher error_handler
trace: switching to run mode 3 for Log::Report::Dispatcher::Callback, accept ALL
dancer2@ankh-morpork:~/MyApp$

**Comment by xsawyerx** [comment]
Cool. Thanks!
